### ISSUE TITLE
Blank json output for all searches

### ISSUE THREAD

**Issue by Jigoku** [joetats/youtube_search#10]
I have been using this snippet for a while:
```
search = json.loads(YoutubeSearch("test", max_results=1).to_json())
videos = search["videos"][0]
link = videos["link"]
print("https://youtube.com" + link)
```
which now results in `list index out of range`

Since today, the json output appears to be returning this for all searches:
```{"videos": []}```

I'm wondering if youtube changed something in the page?

**Comment by nm17** [comment]
Can reproduce, seems like YouTube changed HTML

**Comment by joetats** [comment]
All the video info is now contained inside a Javascript object within a script tag on the returned page, so the parser will need to collect from there. I'm testing out some javascript parsing libraries and hopefully will have something soon

**Comment by alexmercerind** [comment]
Now YouTube randomly returns two types of responses, one within JavaScript and other as HTML... Now we cannot scrape using BeautifulSoup.

I have separately written another script here completely from scratch (without any third party library) and is working with both types of responses.

Feel free to use:
https://github.com/alexmercerind/youtube-search-python

It has lot more information in its search result.

**Comment by gaetan1903** [comment]
My solution is to use selenium for scrapping youtube

**Comment by marsarem** [comment]
Thank you for your solution alexmercerind ! It works perfectly

**Comment by joetats** [comment]
updated to take the "intial data" object, updated to 1.0.0. Will close for now and see how it works
