### ISSUE TITLE
ImportError: cannot import name 'YoutubeSearch'

### ISSUE THREAD

**Issue by cstuart1310** [joetats/youtube_search#11]
Hey, I'm pretty sure this issue is my own fault, but whenever running the example code given I get the error:

`"ImportError: cannot import name 'YoutubeSearch'"`

I've tried installing the library on both windows and linux (I use the windows terminal), both through:

`pip (or pip3) install youtube_search`

and through github via

`pip (or pip3) install git+https://github.com/joetats/youtube_search.git`

This is the example code:

from youtube_search import YoutubeSearch

results = YoutubeSearch('search terms', max_results=10).to_json()

print(results)

# returns a json string

########################################

results = YoutubeSearch('search terms', max_results=10).to_dict()

print(results)
# returns a dictionary

I also have pytube installed if that affects anything?

**Comment by cstuart1310** [comment]
> 
> 
> Hey, I'm pretty sure this issue is my own fault, but whenever running the example code given I get the error:
> 
> `"ImportError: cannot import name 'YoutubeSearch'"`
> 
> I've tried installing the library on both windows and linux (I use the windows terminal), both through:
> 
> `pip (or pip3) install youtube_search`
> 
> and through github via
> 
> `pip (or pip3) install git+https://github.com/joetats/youtube_search.git`
> 
> This is the example code:
> `from youtube_search import YoutubeSearch
> 
> results = YoutubeSearch('search terms', max_results=10).to_json()
> 
> print(results)'
> # returns a json string
> 
> ########################################
> 
> results = YoutubeSearch('search terms', max_results=10).to_dict()
> 
> print(results)
> # returns a dictionary
> 
> I also have pytube installed if that affects anything?

**Comment by cstuart1310** [comment]
Didn't mean to close, I have fat fingers.

**Comment by joetats** [comment]
Ah - on Github I've named it youtube_search, but on PyPI it's youtube-search

There's a separate build process to get it on to PyPI so getting it from github probably won't work. Try installing it and see if that works!

**Comment by cstuart1310** [comment]
Just tried installing youtube-search instead of youtube_search, and have got this error when installing on ubuntu using pip:

`Collecting youtube-search
  Using cached https://files.pythonhosted.org/packages/9a/a7/040944c38b65661fa888fef2364383a1d2ef2d6243e105c81e22324e420b/youtube-search-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-A7TcTe/youtube-search/setup.py", line 1, in <module>
        import pathlib
    ImportError: No module named pathlib

    ----------------------------------------`

and then doing pip install pathlib followed by reinstalling youtube-search causes this error:

`Collecting youtube-search
  Using cached https://files.pythonhosted.org/packages/9a/a7/040944c38b65661fa888fef2364383a1d2ef2d6243e105c81e22324e420b/youtube-search-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zSnIEH/youtube-search/setup.py", line 8, in <module>
        README = (HERE / "README.md").read_text()
    AttributeError: 'PosixPath' object has no attribute 'read_text'

    ----------------------------------------`

however using pip3 install youtube-search on ubuntu or pip install youtube-search on windows results in the original ImportError.

**Comment by joetats** [comment]
I'd guess that this is an environment error based on what you're seeing - pip is probably using python2 but when you use pip3 it's installing to a different python path

Can you try making a virtual environment so everything is consistent? This way the regular pip command will work correctly. For example, on my Mac I need to do the following to keep everything in python3:
```
python3.8 -m venv venv
source venv/bin/activate

pip install youtube-search
```

Windows would be similar:
```
python3.8 -m venv venv
venv\Scripts\activate

pip install youtube-search
```

**Comment by joetats** [comment]
Hi @cstuart1310 did this work? I'll close out the issue if there are no further concerns. Thanks!

**Comment by cstuart1310** [comment]
> Hi @cstuart1310 did this work? I'll close out the issue if there are no further concerns. Thanks!

Hi sorry, got distracted with other projects. Will have another go and get back to you soon

**Comment by cstuart1310** [comment]
> I'd guess that this is an environment error based on what you're seeing - pip is probably using python2 but when you use pip3 it's installing to a different python path
> 
> Can you try making a virtual environment so everything is consistent? This way the regular pip command will work correctly. For example, on my Mac I need to do the following to keep everything in python3:
> 
> ```
> python3.8 -m venv venv
> source venv/bin/activate
> 
> pip install youtube-search
> ```
> 
> Windows would be similar:
> 
> ```
> python3.8 -m venv venv
> venv\Scripts\activate
> 
> pip install youtube-search
> ```

Super sorry, whole thing was my own stupid mistake. I made a file called youtube_search.py and later abandoned it to test using a different filename, meaning that all the files in the test folder were trying to read my youtube_search file instead of the library. Deleting the youtube_search.py that I made fixed all my issues, thanks.

**Comment by joetats** [comment]
no worries! i do that all the time, dang namespace conflicts are tough to track down. Glad you got it going!
