### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by occune** [joetats/youtube_search#13]
Getting 200 None and empty response after invoking a search
```bash
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): youtube.com:443
DEBUG:urllib3.connectionpool:https://youtube.com:443 "GET /results?search_query=tuvan%20throat%20singing&pbj=1 HTTP/1.1" 301 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.youtube.com:443
DEBUG:urllib3.connectionpool:https://www.youtube.com:443 "GET /results?search_query=tuvan%20throat%20singing&pbj=1 HTTP/1.1" 200 None
{"videos": []}
```
youtube-search module is updated to 1.0.0

**Comment by alexmercerind** [comment]
I made a similar module. It has 100% reliable results. Can search for videos and playlists on YouTube. 
Take a look:
https://github.com/alexmercerind/youtube-search-python

Feel free to use.

**Comment by joetats** [comment]
Try the new 1.1.0 release, it should remove the errors that come from missing fields. Let me know if that works!

**Comment by occune** [comment]
its working now, thanks
