### ISSUE TITLE
Slowness

### ISSUE THREAD

**Issue by rasmus-kirk** [joetats/youtube_search#24]
Hi, I've been looking for something like this project and it seems perfect. The only thing that's really nagging me is that it takes so long to return a search query.  I would like to use this to create a script that queries youtube, lets me select a video and opens it in mpv, but the slowness would make that pretty frustrating.

I tried running time on a simple script and got:
```
#Search query results... 
python test.py  0,41s user 0,05s system 5% cpu 8,174 total
```
The script in question is:
```
from youtube_search import YoutubeSearch
results = YoutubeSearch('query', max_results=8).to_json()
print(results)
```
So am I doing something wrong here or is it just inherently slow?

**Comment by madeyoga** [comment]
I think this is fixed in my fork: https://github.com/madeyoga/youtube_search and #25

**Comment by joetats** [comment]
Try the new 1.1.1 version, should be significantly faster after @madeyoga 's updates. I'll check back in a few days to see if that works for you!

**Comment by rasmus-kirk** [comment]
I just tried it, and it works wonderfully! Thank you.

**Comment by joetats** [comment]
Awesome! Thank you @KarukSophia for bringing it up and @madeyoga with the quick fix.

Now to get to the other issues I've been putting off... :)
