### ISSUE TITLE
Empty Results

### ISSUE THREAD

**Issue by x011** [joetats/youtube_search#26]
```
from youtube_search import YoutubeSearch
results = YoutubeSearch('youtube', max_results=10).to_json()
print(results)
```

Returns an empty object:

`{"videos": []}`

I have a working internet connection and no errors are presented.
Any idea why?

**Comment by isagastiberri** [comment]
I'm having this problem too, when I search Navidad (christmas in Spanish) it returns an empty list. But if I search for Christmas, it returns the list. Maybe it can only work with English search words?

**Comment by isagastiberri** [comment]
I'm getting this error if I search Navidad (Christmas in Spanish), but not if I search Christmas and neither with youtube. So I'm not sure what's going on

**Comment by losspamerianos** [comment]
For me changing
`encoded_search = urllib.parse.quote(self.search_terms)`
to
`encoded_search = urllib.parse.quote_plus(self.search_terms)`
did the job.

**Comment by joetats** [comment]
Probably should be quote_plus anyway, I've made the change and it's still working so I'll roll that into the package soon. Thanks for looking into it!
